# Dataset and basic statistics

## Libraries

In [2]:
from tabulate import tabulate
import pandas as pd

## Wheatseed dataset

In [4]:
df = pd.read_csv(
    "/content/wheat-seeds (1).csv",
    header=None,
    names=[
        "Area",
        "Perimeter",
        "Compactness",
        "Length of Kernel",
        "Width of Kernel",
        "Asymmetry Coefficient",
        "Length of Kernel Groove",
        "Class",
    ],
)

In [5]:
df.head()

,Area,Perimeter,Compactness,Length of Kernel,Width of Kernel,Asymmetry Coefficient,Length of Kernel Groove,Class
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,1
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,1
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,1
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,1
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,1

In [6]:
df.describe()

,Area,Perimeter,Compactness,Length of Kernel,Width of Kernel,Asymmetry Coefficient,Length of Kernel Groove,Class
count,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000,210.000000
mean,14.847524,14.559286,0.870999,5.628533,3.258605,3.700201,5.408071,2.000000
std,2.909699,1.305959,0.023629,0.443063,0.377714,1.503557,0.491480,0.818448
min,10.590000,12.410000,0.808100,4.899000,2.630000,0.765100,4.519000,1.000000
25%,12.270000,13.450000,0.856900,5.262250,2.944000,2.561500,5.045000,1.000000
50%,14.355000,14.320000,0.873450,5.523500,3.237000,3.599000,5.223000,2.000000
75%,17.305000,15.715000,0.887775,5.979750,3.561750,4.768750,5.877000,3.000000
max,21.180000,17.250000,0.918300,6.675000,4.033000,8.456000,6.550000,3.000000

In [8]:
def summary_stats(
    df: pd.DataFrame,
    mode: bool = False,
    columns: list[str] | None = None,
    exclude_columns: list[str] | None = None
) -> None:

    result = {}
    for data in df.columns:
        if columns and data not in columns:
            continue
        if exclude_columns and data in exclude_columns:
            continue

        data_max = round(df[data].max(), 2)
        data_min = round(df[data].min(), 2)

        result[data] = {
            "class": data,
            "max": data_max,
            "min": data_min,
            "range": round(data_max - data_min, 2),
            "var": round(df[data].var(), 2),
            "std": round(df[data].std(), 2),
            "median": round(df[data].median(), 2),
            "mean": round(df[data].mean(), 2),
        }
        if mode:
            result[data]["mode"] = df[data].mode().values

    print(
        tabulate(
            pd.DataFrame.from_dict(result.values()),
            headers="keys",
            tablefmt="grid",
            showindex=False,
        ),
    )

In [9]:
summary_stats(df, mode=True, exclude_columns=['Class'])

+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| class                   |   max |   min |   range |   var |   std |   median |   mean | mode                |
+=========================+=======+=======+=========+=======+=======+==========+========+=====================+
| Area                    | 21.18 | 10.59 |   10.59 |  8.47 |  2.91 |    14.36 |  14.85 | [11.23 14.11 15.38] |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| Perimeter               | 17.25 | 12.41 |    4.84 |  1.71 |  1.31 |    14.32 |  14.56 | [13.47]             |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| Compactness             |  0.92 |  0.81 |    0.11 |  0    |  0.02 |     0.87 |   0.87 | [0.8823]            |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| Length of Kernel        |  6.67 |  4.9  |    1.77 |  0.2  |  0.44 |     5.52 |   5.63 | [5.236 5.395]       |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| Width of Kernel         |  4.03 |  2.63 |    1.4  |  0.14 |  0.38 |     3.24 |   3.26 | [3.026]             |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| Asymmetry Coefficient   |  8.46 |  0.77 |    7.69 |  2.26 |  1.5  |     3.6  |   3.7  | [2.129 2.221 2.7  ] |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+
| Length of Kernel Groove |  6.55 |  4.52 |    2.03 |  0.24 |  0.49 |     5.22 |   5.41 | [5.001]             |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+---------------------+

In [10]:
groupby = df.groupby("Class")
groupby_count = groupby.size().reset_index(name="count")
print(tabulate(groupby_count, headers="keys", tablefmt="grid"))

+----+---------+---------+
|    |   Class |   count |
+====+=========+=========+
|  0 |       1 |      70 |
+----+---------+---------+
|  1 |       2 |      70 |
+----+---------+---------+
|  2 |       3 |      70 |
+----+---------+---------+

In [11]:
for name, group_data in groupby:
    print(f"\nClass: {name}")
    summary_stats(group_data)

Class: 1
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| class                   |   max |   min |   range |   var |   std |   median |   mean |
+=========================+=======+=======+=========+=======+=======+==========+========+
| Area                    | 17.08 | 11.23 |    5.85 |  1.48 |  1.22 |    14.36 |  14.33 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Perimeter               | 15.46 | 12.63 |    2.83 |  0.33 |  0.58 |    14.32 |  14.29 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Compactness             |  0.92 |  0.84 |    0.08 |  0    |  0.02 |     0.88 |   0.88 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Length of Kernel        |  6.05 |  4.9  |    1.15 |  0.05 |  0.23 |     5.53 |   5.51 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Width of Kernel         |  3.68 |  2.85 |    0.83 |  0.03 |  0.18 |     3.24 |   3.24 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Asymmetry Coefficient   |  6.68 |  0.77 |    5.91 |  1.38 |  1.17 |     2.55 |   2.67 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Length of Kernel Groove |  5.88 |  4.52 |    1.36 |  0.07 |  0.26 |     5.09 |   5.09 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Class                   |  1    |  1    |    0    |  0    |  0    |     1    |   1    |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+

Class: 2
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| class                   |   max |   min |   range |   var |   std |   median |   mean |
+=========================+=======+=======+=========+=======+=======+==========+========+
| Area                    | 21.18 | 15.38 |    5.8  |  2.07 |  1.44 |    18.72 |  18.33 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Perimeter               | 17.25 | 14.66 |    2.59 |  0.38 |  0.62 |    16.21 |  16.14 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Compactness             |  0.91 |  0.85 |    0.06 |  0    |  0.02 |     0.88 |   0.88 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Length of Kernel        |  6.67 |  5.36 |    1.31 |  0.07 |  0.27 |     6.15 |   6.15 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Width of Kernel         |  4.03 |  3.23 |    0.8  |  0.03 |  0.19 |     3.69 |   3.68 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Asymmetry Coefficient   |  6.68 |  1.47 |    5.21 |  1.4  |  1.18 |     3.61 |   3.64 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Length of Kernel Groove |  6.55 |  5.14 |    1.41 |  0.06 |  0.25 |     5.98 |   6.02 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Class                   |  2    |  2    |    0    |  0    |  0    |     2    |   2    |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+

Class: 3
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| class                   |   max |   min |   range |   var |   std |   median |   mean |
+=========================+=======+=======+=========+=======+=======+==========+========+
| Area                    | 13.37 | 10.59 |    2.78 |  0.52 |  0.72 |    11.84 |  11.87 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Perimeter               | 13.95 | 12.41 |    1.54 |  0.12 |  0.34 |    13.25 |  13.25 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Compactness             |  0.9  |  0.81 |    0.09 |  0    |  0.02 |     0.85 |   0.85 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Length of Kernel        |  5.54 |  4.9  |    0.64 |  0.02 |  0.14 |     5.22 |   5.23 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Width of Kernel         |  3.23 |  2.63 |    0.6  |  0.02 |  0.15 |     2.83 |   2.85 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Asymmetry Coefficient   |  8.46 |  1.66 |    6.8  |  1.79 |  1.34 |     4.84 |   4.79 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Length of Kernel Groove |  5.49 |  4.75 |    0.74 |  0.03 |  0.16 |     5.09 |   5.12 |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+
| Class                   |  3    |  3    |    0    |  0    |  0    |     3    |   3    |
+-------------------------+-------+-------+---------+-------+-------+----------+--------+